### ISSUE TITLE
Issue on the Vue Part of the project

### ISSUE THREAD

**Issue by samprog4u** [prismathic/TestMe#25]
Some of the project that deal with Vue are not working. below are the places noticed so far.

1. Add Teacher doesn't populate the subjects
2. All the Font-Awesome icon are not displaying
3. Add Question is not working
4. Add Examination is not working

**Comment by prismathic** [comment]
Hi @samprog4u 

Have you tried installing all necessary dependencies?
In the event that you're still facing issues after that. Do reach out so we could get on a call to trash it out :)

**Comment by samprog4u** [comment]
Yes, I do.

I followed the read-me from A-Z even on the process, I fixed some things on the Migrate issue and Seeding stuff. But due to the fact that am not conversant with Vue so that was what makes me reachout.

Thenk you for your response.

**Comment by codewarrior4** [comment]
I am facing the same issue as @samprog4u is facing

**Comment by prismathic** [comment]
@samprog4u @codewarrior4 my sincere apologies for my late response.
Kindly make use of the `develop` branch as opposed to the current `master` branch. It contains most of the updates on the Vue portion of the project

**Comment by prismathic** [comment]
This has now been resolved. Closing it for the time being. It can be reopened in the event that there's another issue
